// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_WriterStatu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_WriterStatu));
        
        string IMigrationMetadata.Id
        {
            get { return "202210100802204_mig_WriterStatu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
